import type { EventItemProps } from "@/components/domain/event-item";
import type { TimelineEvent } from "@/components/domain/event-timeline";

// ── Short timeline (3 events, for EventTimeline) ─

export const sampleTimelineEvents: TimelineEvent[] = [
  {
    id: 1,
    type: "result",
    player1: { name: "Max Mustermann" },
    player2: { name: "Anna Schmidt" },
    winnerId: "player1",
    scores: [[6, 4], [7, 5]],
    rankBefore: 5,
    rankAfter: 3,
    time: "14:30",
    group: "Heute",
    groupDate: "12.02.2026",
  },
  {
    id: 2,
    type: "challenge",
    challenger: { name: "Tom Weber" },
    challengee: { name: "Lisa Müller" },
    time: "11:45",
    group: "Heute",
    groupDate: "12.02.2026",
  },
  {
    id: 3,
    type: "new_player",
    player: { name: "Sarah Hoffmann" },
    startingRank: 12,
    time: "10:30",
    group: "Gestern",
    groupDate: "11.02.2026",
  },
];

// ── Season events (append to timeline) ─────────

export const seasonStartEvent: TimelineEvent = {
  id: 5,
  type: "season_start",
  seasonName: "Sommer 2026",
  playerCount: 24,
  time: "08:00",
  group: "Letzte Woche",
  groupDate: "05.02.2026",
};

export const seasonEndEvent: TimelineEvent = {
  id: 6,
  type: "season_end",
  seasonName: "Winter 2025/26",
  winnerName: "Julia Fischer",
  time: "17:00",
  group: "Vor 2 Wochen",
  groupDate: "29.01.2026",
};

// ── Feed events (page-level) ───────────────────

export const feedEvents: TimelineEvent[] = [
  {
    id: "e1",
    type: "result",
    player1: { name: "Julia Fischer" },
    player2: { name: "Anna Schmidt" },
    winnerId: "player1",
    scores: [[6, 3], [7, 5]],
    rankBefore: 2,
    rankAfter: 1,
    time: "14:30",
    group: "Heute",
    groupDate: "12.02.2026",
    href: "/matches/m3",
  },
  {
    id: "e2",
    type: "challenge",
    challenger: { name: "Tom Weber" },
    challengee: { name: "Anna Schmidt" },
    time: "11:45",
    group: "Heute",
    groupDate: "12.02.2026",
    href: "/matches/m2",
  },
  {
    id: "e3",
    type: "withdrawal",
    player: { name: "Felix Wagner" },
    opponent: { name: "Paul Becker" },
    reason: "Terminkonflikt",
    time: "16:20",
    group: "Gestern",
    groupDate: "11.02.2026",
    href: "/matches/m5",
  },
  {
    id: "e4",
    type: "forfeit",
    player: { name: "Marie Koch" },
    opponent: { name: "Laura Richter" },
    reason: "Verletzung",
    time: "09:15",
    group: "Gestern",
    groupDate: "11.02.2026",
    href: "/matches/m6",
  },
  {
    id: "e6",
    type: "new_player",
    player: { name: "Emma Bauer" },
    startingRank: 12,
    time: "10:30",
    group: "Vor 3 Tagen",
    groupDate: "09.02.2026",
    href: "/player/p12",
  },
  {
    id: "e7",
    type: "season_start",
    seasonName: "Sommer 2026",
    playerCount: 24,
    time: "08:00",
    group: "Letzte Woche",
    groupDate: "05.02.2026",
  },
  {
    id: "e8",
    type: "unavailable",
    player: { name: "Sophie Hoffmann" },
    returnDate: "15.03.2026",
    time: "12:00",
    group: "Letzte Woche",
    groupDate: "05.02.2026",
    href: "/player/p6",
  },
  {
    id: "e9",
    type: "season_end",
    seasonName: "Winter 2025/26",
    winnerName: "Julia Fischer",
    time: "17:00",
    group: "Vor 2 Wochen",
    groupDate: "29.01.2026",
  },
];

// ── All event types (for EventItem AllTypes) ───

export const allEventTypes: EventItemProps[] = [
  // Public events
  { type: "result", player1: { name: "Max M." }, player2: { name: "Anna S." }, winnerId: "player1", scores: [[6, 4], [3, 6], [7, 5]], rankBefore: 5, rankAfter: 3, time: "14:30" },
  { type: "challenge", challenger: { name: "Tom W." }, challengee: { name: "Lisa M." }, time: "11:45" },
  { type: "withdrawal", player: { name: "Felix W." }, opponent: { name: "Anna Schmidt" }, reason: "Terminkonflikt", time: "16:20" },
  { type: "forfeit", player: { name: "Marie K." }, opponent: { name: "Tom Weber" }, reason: "Verletzung", time: "09:15" },
  { type: "new_player", player: { name: "Sarah H." }, startingRank: 12, time: "10:30" },
  { type: "unavailable", player: { name: "Erik M." }, returnDate: "20.03.2026", time: "12:00" },
  { type: "unavailable", player: { name: "Sophie H." }, time: "15:45" },
  // Personal notification events
  { type: "challenged", challenger: { name: "Tom W." }, challengee: { name: "Max M." }, personal: true, time: "16:00" },
  { type: "challenge_accepted", challenger: { name: "Max M." }, challengee: { name: "Anna S." }, personal: true, time: "15:30" },
  { type: "challenge_withdrawn", player: { name: "Felix W." }, opponent: { name: "Max M." }, personal: true, time: "14:45" },
  { type: "date_proposed", player: { name: "Anna S." }, opponent: { name: "Max M." }, proposedDate: "Sa, 15.03.2026 18:00", personal: true, time: "13:20" },
  { type: "date_accepted", player: { name: "Max M." }, opponent: { name: "Anna S." }, acceptedDate: "Sa, 15.03.2026 18:00", personal: true, time: "12:10" },
  { type: "date_reminder", player: { name: "Max M." }, opponent: { name: "Tom W." }, daysLeft: 3, personal: true, time: "09:00" },
  { type: "result_entered", player1: { name: "Anna S." }, player2: { name: "Max M." }, scores: [[6, 4], [7, 5]], personal: true, time: "17:00" },
  { type: "result_confirmed", player1: { name: "Max M." }, player2: { name: "Anna S." }, scores: [[6, 4], [7, 5]], personal: true, time: "17:30" },
  { type: "result_disputed", player1: { name: "Tom W." }, player2: { name: "Max M." }, personal: true, time: "18:00" },
  { type: "announcement", message: "Platzsperre am 20.03. wegen Sanierung", adminName: "Admin Peter", time: "08:00" },
  { type: "deadline_exceeded", player: { name: "Max M." }, opponent: { name: "Lisa M." }, daysOver: 3, personal: true, time: "07:00" },
];

// ── Combined feed (notifications page) ─────────

export const allEvents: TimelineEvent[] = [
  {
    id: "n1",
    type: "challenge",
    challenger: { name: "Max Braun" },
    challengee: { name: "Lisa Müller" },
    time: "16:50",
    group: "Heute",
    groupDate: "12.02.2026",
    unread: true,
    href: "/matches/m1",
  },
  {
    id: "e1",
    type: "result",
    player1: { name: "Julia Fischer" },
    player2: { name: "Anna Schmidt" },
    winnerId: "player1",
    scores: [[6, 3], [7, 5]],
    rankBefore: 2,
    rankAfter: 1,
    time: "14:30",
    group: "Heute",
    groupDate: "12.02.2026",
    unread: true,
    href: "/matches/m3",
  },
  {
    id: "n3",
    type: "unavailable",
    player: { name: "Sophie Hoffmann" },
    time: "11:45",
    group: "Heute",
    groupDate: "12.02.2026",
    unread: true,
    href: "/player/p6",
  },
  {
    id: "e2",
    type: "challenge",
    challenger: { name: "Tom Weber" },
    challengee: { name: "Anna Schmidt" },
    time: "11:00",
    group: "Heute",
    groupDate: "12.02.2026",
    href: "/matches/m2",
  },
  {
    id: "e3",
    type: "withdrawal",
    player: { name: "Felix Wagner" },
    opponent: { name: "Paul Becker" },
    reason: "Terminkonflikt",
    time: "16:20",
    group: "Gestern",
    groupDate: "11.02.2026",
    href: "/matches/m5",
  },
  {
    id: "e4",
    type: "forfeit",
    player: { name: "Marie Koch" },
    opponent: { name: "Laura Richter" },
    reason: "Verletzung",
    time: "09:15",
    group: "Gestern",
    groupDate: "11.02.2026",
    href: "/matches/m6",
  },
  {
    id: "e6",
    type: "new_player",
    player: { name: "Emma Bauer" },
    startingRank: 12,
    time: "10:30",
    group: "Vor 3 Tagen",
    groupDate: "09.02.2026",
    href: "/player/p12",
  },
  {
    id: "e7",
    type: "season_start",
    seasonName: "Sommer 2026",
    playerCount: 24,
    time: "08:00",
    group: "Letzte Woche",
    groupDate: "05.02.2026",
  },
  {
    id: "e8",
    type: "unavailable",
    player: { name: "Sophie Hoffmann" },
    returnDate: "15.03.2026",
    time: "12:00",
    group: "Letzte Woche",
    groupDate: "05.02.2026",
    href: "/player/p6",
  },
  {
    id: "e9",
    type: "season_end",
    seasonName: "Winter 2025/26",
    winnerName: "Julia Fischer",
    time: "17:00",
    group: "Vor 2 Wochen",
    groupDate: "29.01.2026",
  },
];
